#!/usr/bin/env python3
import glob
import select
from evdev import InputDevice, ecodes

# 3DSLinux Input Tester
#
# This program introduces how the 3DS controls appear to Linux.
# The next example, buttontesttui.py, will use this same input handling to build
# a terminal interface.

bindings = {}

# buttonbindings.txt maps Linux event codes to 3DS button names.
#
# For example:
#
# A=304
# B=305
# X=307
#
# This means that when Linux reports event code 304,
# we know that it came from the A button.
with open("buttonbindings.txt") as f:
    for line in f:
        line = line.strip()

        if not line or "=" not in line:
            continue

        name, code = line.split("=", 1)
        bindings[int(code)] = name


# Linux exposes input devices as /dev/input/event*.
# evdev lets us read the events generated by those devices.
devices = []

for path in glob.glob("/dev/input/event*"):
    try:
        device = InputDevice(path)
        devices.append(device)
        print(f"Found: {device.name} ({path})")
    except PermissionError:
        pass


print("\nInput Tester")
print("============")
print("Press any button or move the Slide Pad.\n")


# Keep track of which buttons are currently pressed.
buttons = {name: False for name in bindings.values()}

# The Slide Pad sends X and Y as separate events.
# Keeping the previous value lets us print both axes together.
joy_x = 0
joy_y = 0


while True:
    # Wait until one of the input devices has an event.
    readable, _, _ = select.select(devices, [], [])

    for device in readable:
        for event in device.read():

            # Buttons such as A, B, HOME, and START use EV_KEY.
            if event.type == ecodes.EV_KEY:
                button = bindings.get(event.code)

                if button is None:
                    continue

                if event.value == 1:
                    buttons[button] = True
                    print(f"[BUTTON] {button} pressed")

                elif event.value == 0:
                    buttons[button] = False
                    print(f"[BUTTON] {button} released")


            # The Slide Pad uses relative movement events.
            elif event.type == ecodes.EV_REL:

                if event.code == ecodes.REL_X:
                    joy_x = event.value
                    print(f"[SLIDEPAD] X: {joy_x:+d} Y: {joy_y:+d}")

                elif event.code == ecodes.REL_Y:
                    joy_y = event.value
                    print(f"[SLIDEPAD] X: {joy_x:+d} Y: {joy_y:+d}")